# Generated by Django 3.2.12 on 2022-02-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(help_text='Razón social registrada en SUNAT', max_length=120, verbose_name='Razón Social')),
                ('Ruc', models.BigIntegerField(verbose_name='RUC')),
                ('Direccion', models.CharField(max_length=255, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
    ]
