# Generated by Django 3.2.12 on 2022-02-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_alter_editorial_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='slug',
            field=models.SlugField(default='Nada'),
            preserve_default=False,
        ),
    ]
