# Generated by Django 3.2.12 on 2022-02-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_editorial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
