# Generated by Django 3.2.12 on 2022-02-25 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='autor',
            name='Edad',
            field=models.DateField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Profesion',
            field=models.CharField(choices=[('Dr', 'Doctor'), ('Ing', 'Ingeniero'), ('Per', 'Periodista')], max_length=3, verbose_name='Profesión'),
        ),
    ]
