# Generated by Django 3.2.12 on 2022-02-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0002_auto_20220225_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='Edad',
        ),
    ]
