# Generated by Django 3.2.12 on 2022-02-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_remove_autor_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='Edad',
            field=models.DateField(default='2022-01-01', verbose_name='Edad'),
            preserve_default=False,
        ),
    ]
