# Generated by Django 3.2.12 on 2022-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0004_autor_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='Edad',
        ),
        migrations.AddField(
            model_name='autor',
            name='Nacimiento',
            field=models.DateField(default='1979-02-14', verbose_name='Nacimiento'),
            preserve_default=False,
        ),
    ]
