# Generated by Django 3.2.12 on 2022-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0005_auto_20220225_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='Curriculum',
            field=models.FileField(blank=True, null=True, upload_to='file/Autor/', verbose_name='Curriculum'),
        ),
        migrations.AddField(
            model_name='autor',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/Autor/', verbose_name='Foto'),
        ),
    ]
